version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Check if fastai base image created
      - base_image="fastai"
      - build_base() { echo "Build and push fastai base image" && docker build -t ${base_image}:latest fastai-base && docker tag ${base_image}:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${base_image}:latest && docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${base_image}:latest; }
      - imageCount=$(aws ecr describe-images --repository-name $base_image --query 'imageDetails[] | length(@)' --region $AWS_DEFAULT_REGION)
      - if [ "$imageCount" -eq "0" ]; then build_base; else echo "Image: ${base_image} already uploaded to repository"; fi
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image with aws_account_id=$AWS_ACCOUNT_ID and aws_region=$AWS_DEFAULT_REGION
      - docker build --build-arg aws_account_id=$AWS_ACCOUNT_ID --build-arg aws_region=$AWS_DEFAULT_REGION -t $IMAGE_REPO_NAME:$IMAGE_TAG container
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
